### ISSUE TITLE
igc enable should provide a package.json if one does not exist in the project.

### ISSUE THREAD

**Issue by mjperrins** [ibm-garage-cloud/planning#145]
igc enable should provide a package.json if one does not exist in the project.

**Comment by seansund** [comment]
Why do you want a package.json? If the project is a node project then the package.json is required already. IF the project is a Java project then the package.json isn't necessary. I like to add one as a way to have some consistency of scripts across projects but I'm not sure if this is something that should be required.

If this is about the tagging mechanism with `release-it`, then the package.json is not required for that to work. In fact, we completely ignore the package.json file when generating the next version number because of issues created when the pipeline alters files in the Git repo and commits them...

**Comment by seansund** [comment]
Replaced with #155
