### ISSUE TITLE
RJ can use an automated script to set up access to the clusters and services in his account so that he can control who can do what

### ISSUE THREAD

**Issue by seansund** [ibm-garage-cloud/planning#22]
Acceptance Criteria:
- Script that creates an `Account Admin` Access Group
- Script that creates a Resource Group
- Script that creates an `Admin` Access Group for the Resource Group
- Script that creates a `User` Access Group for the Resource Group
- Script that applies Role Based Access Control (RBAC) for the cluster(s) in the Resource Group

**Comment by bwoolf1** [comment]
Submitted help ticket, case number CS1673167.

Need the CLI command to create a policy that allows the user to create any service and add the new instance to a particular resource group

I can create a policy in the console that gives users the ability to create a service and specify the resource group. I need to know how to do this in the CLI. The CLI command I'm using should do the same thing but does something different that isn't working.

In the console, when I create a policy for All Identity and Access enabled services for a resource group, it creates two policies. The Resource group access policy is Viewer role with these details:

RESOURCE_GROUP_NAME resource group
resourceType string equals resource-group, resource string equals RESOURCE_GROUP_NAME

This enables the user to create any service and add the new instance to the resource group, which is what I want.

I'm trying to create the same policy using the CLI. When I run this command:

$ ibmcloud iam access-group-policy-create GROUP_NAME --roles Viewer --resource-group-name RESOURCE_GROUP_NAME --attributes "resourceType=resource-group,resource=RESOURCE_GROUP_NAME"

the policy is Viewer role with these details:

All service in RESOURCE_GROUP_NAME resource group
resourceType string equals resource-group, resource string equals RESOURCE_GROUP_NAME

Notice the additional "All service in" part. This policy doesn't work. When the user tries to create a service, they can't select the resource group.

Where does that "All service in" part come from? How do I modify the access-group-policy-create command to not add it, so that the command produces the same policy that the console does?

If someone from L3 wants to share a screen with me, I can show them the problem. To do so, I'll need to add them to an access group so that they can experience the problem.

Thanks.

**Comment by bwoolf1** [comment]
Opened support case CS1760962: CLI doesn't recognize service access roles for IAM services

**Comment by bwoolf1** [comment]
Opened support case CS1737681: Kubernetes cluster failed to delete with error `Worker not found` error -- Long discussion of what a nightmare IKS api keys and users' infrastructure permissions can become

**Comment by bwoolf1** [comment]
Opened two related ideas:
- [IDEAINT-I-3145: Bug: IKS api keys may not allow cluster creation and deletion](https://internal-ibmcloud.ideas.aha.io/ideas/IDEAINT-I-3145)
- [IDEAINT-I-3131: Improve IAM access groups to include infrastructure permissions and own IKS api keys](https://internal-ibmcloud.ideas.aha.io/ideas/IDEAINT-I-3131)

**Comment by bwoolf1** [comment]
Opened idea [IDEAINT-I-3050: Improve the CLI command to create a policy with Resource group access Viewer role for a resource group](https://internal-ibmcloud.ideas.aha.io/ideas/IDEAINT-I-3050)

**Comment by bwoolf1** [comment]
Opened idea [IDEAINT-I-3149: Better GUI to show how IAM roles and permissions are related](https://internal-ibmcloud.ideas.aha.io/ideas/IDEAINT-I-3149)
