### ISSUE TITLE
The documentation for plan installation is confusing and is not clear what scripts for acp map to the admin, environment and users

### ISSUE THREAD

**Issue by mjperrins** [ibm-garage-cloud/planning#261]
The documentation for plan installation is confusing and is not clear what scripts for acp map to the admin, environment and users

The scripts are named like this ? 
![Screen Shot 2020-04-05 at 3.03.07 PM.png](https://images.zenhubusercontent.com/570fff13bf93871ccd99764f/1f13ab94-ee1d-46c7-a3ad-6b8c1402aed5)

The documentation names this ? 
![Screen Shot 2020-04-05 at 3.01.52 PM.png](https://images.zenhubusercontent.com/570fff13bf93871ccd99764f/ab1fcb1e-4945-487c-8547-6602855539c4)

Is Acct = Environment management or Admin ?

The documentation further down uses a reference to a script that does not exist ?

![Screen Shot 2020-04-05 at 3.01.32 PM.png](https://images.zenhubusercontent.com/570fff13bf93871ccd99764f/28013ccf-8308-4959-a53b-57b83e939f7d)

**Comment by bwoolf1** [comment]
The Guide explains the basics at least of when and how to use the Access Group scripts.

Plan Installation > [Roles](https://cloudnativetoolkit.dev/admin/plan-installation#roles) explains the four types of users involved:
>- **Account owner**: The user who owns the account.
>- **Account administrators**: Account owner or other users with account management permissions
>- **Environment administrators**: Users in the account with permissions to create services in the environment’s resource group
>- **Environment users**: Users in the account with permissions to manage existing services in the environment’s resource group (e.g. developers, data scientists, etc.)

Plan Installation > [Access group for account administrators](https://cloudnativetoolkit.dev/admin/plan-installation#access-group-for-account-administrators) says:
>- Create a new access group, name it something like ACCOUNT-ADMIN (all capital letters) (or name it after your account)
>- Run the script `./terraform/scripts/acp-acct`, which will add the necessary policies to the access group
>- Add the account administrator(s) to the group

Configure Account > [Access group for environment administrators](https://cloudnativetoolkit.dev/admin/config-account#access-group-for-environment-administrators) says:
>- Create a new access group, name it something like <resource_group>-ADMIN (all capital letters)
>- Run the script `./terraform/scripts/acp-admin`, which will add the necessary policies to the access group
>- Add the environment administrator(s) to the group

Configure Account > [Access group for environment users](https://cloudnativetoolkit.dev/admin/config-account#access-group-for-environment-users) says:
>- Create a new access group, name it something like <resource_group>-USER (all capital letters)
>- Run the script `./terraform/scripts/acp-user`, which will add the necessary policies to the access group
>- Add the users to the group

So that explains the three scripts -- `acp-acct`, `acp-admin`, and `acp-user` -- and how to use them to create three Access Groups.

**Comment by bwoolf1** [comment]
Issue #272 changes the name of the second role from Account administrators to Account managers, with corresponding changes to the names of the access group and script.
