### ISSUE TITLE
TriggerTemplates no longer work on OCP 4.6 with OpenShift Pipeline (tekton) Operator 1.2.x

### ISSUE THREAD

**Issue by csantanapr** [ibm-garage-cloud/planning#752]
Pipelines fail to start when they are initiated with a Git WebHook

```
line 5: params.gitrepositoryurl: not found
Cloning into '/source'...
fatal: protocol '' is not supported
```

OCP 4.6 with OpenShift Pipeline (tekton) Operator 1.2.x the way we create the TriggerTemplates to handle webhooks no longer work.

TriggerTemplates now require to use `$(tt.params)`

Breaking Changes 🚨
Remove deprecated $(params) (#690)
This is a breaking change as this PR remove complete support of $(params) and moved to $(tt.params) in order to avoid confusion between resourcetemplates and triggertemplate params

https://github.com/tektoncd/triggers/releases/tag/v0.7.0

**Comment by seansund** [comment]
Do we need to support Tekton v0.4.0 anymore?

**Comment by csantanapr** [comment]
@seansund I if it's difficult I would say no, trigger v0.4 was for pipelines 1.0 in ocp 4.4 and redhat already GA 4.7

**Comment by seansund** [comment]
Supporting 0.4 is difficult because there is no way to determine the version reliably and no schema validation for this one... 

At one point we looked up the Tekton trigger version from an annotation on the Tekton deployment in the `openshift-operators` project but that requires a lot of permission to access and would fail `oc pipeline` if it was run as a basic user.

For the event listener we try to create a 0.6+ yaml and if it fails we fall back to 0.4. With the TriggerTemplate the change is in a string value and won't fail at creation time.

I've implemented the TriggerTemplate change with the assumption that we are on 0.6+.

**Comment by seansund** [comment]
Perhaps we should remove the fallback logic from TriggerTemplate and allow the user to pass a flag if they are on 0.4. In that scenario they would run it without the flag the the first time and see `oc pipeline` fail because of the TriggerTemplate. We would include a message that says something like "It looks like you may be using a different version of the Tekton triggers. Check your version by having an admin run `VERSION=$(oc get ...)` and try running again with --triggerVersion {VERSION}".
