### ISSUE TITLE
Move away from -<buildnumber> in the pipelines to SemVer so use of Artifactory is supported in IBM Cloud Pak for Multi Cloud Manager

### ISSUE THREAD

**Issue by mjperrins** [ibm-garage-cloud/planning#90]
**Is your feature request related to a problem? Please describe.**
Move away from -<buildnumber> in the pipelines to SemVer so use of Artifactory is supported in IBM Cloud Pak for Multi Cloud Manager

https://semver.org/

**Describe the solution you'd like**
In testing using Cloud Native Toolkit with other IBM Cloud Paks, it has been discovered that MCM will not support a version that has been taged `0.0.0-<buildnumber>` it supports vanilla SemVer. To enable the broader inclusion of Cloud Native Toolkit into the developer end to end experience I am proposing we move from current format to replace the patch level with the build number.  ie. `1.1.43` 

The plan is to still use GitOps and Argo for namespace to namespace deployment, but for deployment to other clusters ie, cluster to cluster deployments CP4MCM can be used with all the other benefits it brings 

**Describe alternatives you've considered**
Its a bug in MCM, so the only work around is to adopt SemVer 

**Additional context**

Here is a screenshot of MCM using the Artificatory instance from Cloud Native Tool Kit installation.

![image](https://user-images.githubusercontent.com/16599999/74276115-bb77e600-4cda-11ea-8463-7eb21424d602.png)

**Comment by seansund** [comment]
We should use Git tags as the source for the SemVer (major.minor.patch). The major and minor versions should come from the contents within the repo (e.g. the package.json or gradle file). The build will supply the patch version number. If there are no semantic version tags on the repo then the patch version will come from the repo contents. If there is a semantic version tag on the repo then the build should increment the number.

The build should also apply the new tag version to the commit as part of the build process

**Comment by seansund** [comment]
In addition to coming into compliance with SemVer standards and enabling support for Multi Cloud Manager, this approach with address two important issues:

- Tekton does not have the notion of a sequential build number so it was using a short form of the hash as the snapshot value. This change will bring consistency across different pipeline tools because it will depend on Git as the source of truth for the version tag
- The build numbers in Jenkins are dependent upon the particular Jenkins instance. If the instance is destroyed and rebuilt today, the build numbers would need to be reset to the previous build number to prevent overwrites of images. With this new approach, Git is the repository of the version information so the process of restoring the pipeline instance (or relocating it) is simplified

**Comment by mjperrins** [comment]
This looks like a perfect package to use https://www.npmjs.com/package/release-it and we will need to modify these repos
- [ ] `igc enable` source for Jenkins
- [ ] Tekton Tasks repo
- [ ] The 5 Code Patterns repos

**Comment by seansund** [comment]
> This looks like a perfect package to use https://www.npmjs.com/package/release-it and we will need to modify these repos
> 
> * [ ]  `igc enable` source for Jenkins
> * [ ]  Tekton Tasks repo
> * [ ]  The 5 Code Patterns repos
> * [ ]  Update the Documentation
> * [ ]  Add MCM Section on CD with MCM

One of the features of `release-it` is to update the version number in package.json as well as tagging the the commit with the version number. In order for that to work without getting us into an infinite build loop we will need to update the logic to kick off the build. 

One thought is to check the files that have been changed and don't run the build if only the package.json was changed. The command would be something like this - 
```
git diff-tree --no-commit-id --name-only -r {commit hash}
```

**Comment by mjperrins** [comment]
Is this closed now @seansund ?

**Comment by seansund** [comment]
Yes
